### ISSUE TITLE
Changing resolution in windowed mode

### ISSUE THREAD

**Issue by Keith94** [ThirteenAG/d3d9-wrapper#1]
I tested the d3d9 wrapper in Prince of Persia: Sands of Time to force windowed mode.

It works, however changing the in-game resolution to something else will set the game to fullscreen mode.

Is there a way the d3d9 wrapper can prevent that if forcing windowed mode?

**Comment by ThirteenAG** [comment]
Maybe, but there's plenty of windowed mode solutions already, this wrapper is not it. Better try wndmode.ini from asi loader.

**Comment by Keith94** [comment]
>Better try wndmode.ini from asi loader.

I tried it, but it breaks graphics in this game (and its sequels I think). This wrapper seemed appealing to me.

![pop_2017_04_24_05_50_21_800](https://cloud.githubusercontent.com/assets/5490615/25337809/1e3fe4fe-28b2-11e7-8d18-fede561dc639.png)

**Comment by ThirteenAG** [comment]
I see, well, maybe setting windowed on reset will help. I'll try.

**Comment by ThirteenAG** [comment]
Updated.

**Comment by Keith94** [comment]
That did the trick. :)

Btw, you should disable `FPSLimit` by default. Similar to d3d8-wrapper.
