### ISSUE TITLE
[NFSU2] Windowed mode doesn't work at all

### ISSUE THREAD

**Issue by TheComputerGuy96** [ThirteenAG/d3d9-wrapper#2]
@ThirteenAG I turned windowed mode on in d3d9.ini file but the game still runs in fullscreen (I'm running the game in native resolution and I'm using your widescreen fix)

Note: Alt+Enter does nothing

**Comment by Keith94** [comment]
@TheComputerGuy96 Check https://pcgamingwiki.com/wiki/Need_for_Speed:_Underground_2#Windowed
